#
# Copyright (C) 2019 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Init (Android project name autogenerated by vendor_buildinfo.sh as a system.prop)
PRODUCT_PROPERTY_OVERRIDES += \
    ro.boot.project_name=18821 \
    ro.vendor.boot.project_name=18821 \
    ro.product.vendor.name=OnePlus7Pro


# build properties
PRODUCT_PROPERTY_OVERRIDES += \
    persist.sys.oem.region=OverSeas \
    persist.sys.oem_smooth=1 \
    ro.product.device=guacamole \
    ro.product.vendor.device=OnePlus7Pro \
    ro.product.vendor.brand=OnePlus \
    ro.product.vendor.manufacturer=OnePlus \
    ro.vendor.build.real.device=true \
    vendor.product.device=guacamole \
    vendor.product.manufacturer=OnePlus
